@extends('layouts.store')
@section('title', 'Carrito | Esencia Store')
@section('content')
<section class="page-hero page-hero-small"><div class="container"><p class="eyebrow">Tu selección</p><h1>Carrito</h1></div></section>
<section class="section"><div class="container">
@if($cart['items']->isEmpty())<div class="empty-state"><span>◌</span><h2>Tu carrito está vacío</h2><p>Todavía no has agregado productos.</p><a class="button button-primary" href="{{ route('shop') }}">Explorar productos</a></div>
@else<div class="cart-layout"><div class="cart-items"><div class="cart-heading"><h2>Productos <span>{{ $cart['count'] }}</span></h2><form method="post" action="{{ route('cart.clear') }}">@csrf @method('delete')<button>Vaciar carrito</button></form></div>
@foreach($cart['items'] as $item)<article class="cart-item"><div class="cart-thumb">@if($item['product']->image)<img src="{{ asset('storage/'.$item['product']->image) }}" alt="">@else<span>ES</span>@endif</div><div class="cart-copy"><p>{{ $item['product']->brand ?: 'HGW' }}</p><h3><a href="{{ route('products.show', $item['product']) }}">{{ $item['product']->name }}</a></h3><span>{{ $item['product']->code ? 'Cód. '.$item['product']->code : 'Código por confirmar' }}</span></div><form class="quantity-form" method="post" action="{{ route('cart.update', $item['product']) }}">@csrf @method('patch')<label>Cantidad<input type="number" name="quantity" value="{{ $item['quantity'] }}" min="0" max="99" onchange="this.form.submit()"></label></form><strong>{{ $item['product']->price ? '$ '.number_format($item['lineTotal'], 0, ',', '.') : 'Por confirmar' }}</strong><form method="post" action="{{ route('cart.destroy', $item['product']) }}">@csrf @method('delete')<button class="remove-button" aria-label="Quitar producto">×</button></form></article>@endforeach
</div><aside class="cart-summary"><p class="eyebrow">Resumen</p><h2>Tu pedido</h2><dl><div><dt>Total productos</dt><dd>{{ $cart['count'] }}</dd></div><div><dt>Envío</dt><dd>Por confirmar</dd></div><div class="summary-total"><dt>Subtotal</dt><dd>$ {{ number_format($cart['subtotal'], 0, ',', '.') }}</dd></div></dl><a class="button button-primary button-full" href="{{ route('checkout.index') }}">Finalizar pedido →</a><p>La disponibilidad y el valor del envío se confirman antes de completar la compra.</p></aside></div>@endif
</div></section>
@endsection
