@extends('layouts.store')
@section('title', 'Finalizar pedido | Esencia Store')
@section('content')
<section class="page-hero page-hero-small"><div class="container"><p class="eyebrow">Último paso</p><h1>Coordina tu pedido</h1><p>Completa tus datos y envía la solicitud por WhatsApp.</p></div></section>
<section class="section"><div class="container checkout-layout">
    <form class="checkout-form" method="post" action="{{ route('checkout.store') }}" data-checkout-form>@csrf<input type="hidden" name="checkout_mode" value="{{ $checkoutMode }}">
        @if($errors->any())<div class="form-alert" role="alert"><strong>Revisa los datos del pedido.</strong><span>Completa los campos marcados para continuar a WhatsApp.</span></div>@endif
        @if($errors->has('checkout'))<div class="form-alert" role="alert">{{ $errors->first('checkout') }}</div>@endif
        <fieldset><legend><span>01</span> Información de contacto</legend><div class="form-grid"><label class="field-wide">Nombre completo *<input name="name" value="{{ old('name') }}" autocomplete="name" required>@error('name')<small>{{ $message }}</small>@enderror</label><label>Teléfono *<input name="phone" value="{{ old('phone') }}" autocomplete="tel" inputmode="tel" required>@error('phone')<small>{{ $message }}</small>@enderror</label><label>Correo electrónico<input type="email" name="email" value="{{ old('email') }}" autocomplete="email">@error('email')<small>{{ $message }}</small>@enderror</label></div></fieldset>
        <fieldset><legend><span>02</span> Datos de entrega</legend><div class="form-grid"><label>Departamento *<input name="department" value="{{ old('department') }}" autocomplete="address-level1" required>@error('department')<small>{{ $message }}</small>@enderror</label><label>Ciudad / municipio *<input name="city" value="{{ old('city') }}" autocomplete="address-level2" required>@error('city')<small>{{ $message }}</small>@enderror</label><label class="field-wide">Dirección *<input name="address" value="{{ old('address') }}" autocomplete="street-address" required>@error('address')<small>{{ $message }}</small>@enderror</label><label>Barrio<input name="neighborhood" value="{{ old('neighborhood') }}"></label><label class="field-wide">Indicaciones<textarea name="notes" rows="4" placeholder="Referencias u observaciones para coordinar la entrega">{{ old('notes') }}</textarea>@error('notes')<small>{{ $message }}</small>@enderror</label></div></fieldset>
        <fieldset><legend><span>03</span> Método de entrega</legend><div class="delivery-option"><i></i><div><strong>Coordinar entrega</strong><span>Definiremos contigo disponibilidad, envío y forma de pago.</span></div></div></fieldset>
        <button class="button button-primary button-full checkout-submit" type="submit" @disabled($cart['items']->isEmpty())><span>Enviar pedido por WhatsApp</span><span aria-hidden="true">→</span></button>
    </form>
    <aside class="order-review"><p class="eyebrow">Resumen</p><h2>Tu pedido</h2>@forelse($cart['items'] as $item)<div class="review-item"><div><strong>{{ $item['product']->name }}</strong><span>Cantidad: {{ $item['quantity'] }}</span></div><b>{{ $item['product']->price ? '$ '.number_format($item['lineTotal'], 0, ',', '.') : 'Por confirmar' }}</b></div>@empty<p>Tu carrito está vacío.</p>@endforelse<div class="review-total"><span>Subtotal</span><strong>$ {{ number_format($cart['subtotal'], 0, ',', '.') }}</strong></div><p class="review-note">No realizaremos ningún cobro desde este formulario. El pedido se coordina directamente por WhatsApp.</p></aside>
</div></section>
@endsection
